# "databases" should be URLs to CSV files with the name of the table as the key.   
databases:
  core:
    salesman: https://raw.githubusercontent.com/freestackinitiative/teachingdb_data/main/data/core/SALESMAN.csv
    customer: https://raw.githubusercontent.com/freestackinitiative/teachingdb_data/main/data/core/CUSTOMER.csv
    order_details: https://raw.githubusercontent.com/freestackinitiative/teachingdb_data/main/data/core/ORDERDETAILS.csv
    foods: https://raw.githubusercontent.com/freestackinitiative/teachingdb_data/main/data/core/foods.csv
    company: https://raw.githubusercontent.com/freestackinitiative/teachingdb_data/main/data/core/company.csv
    movies: https://raw.githubusercontent.com/freestackinitiative/teachingdb_data/main/data/core/movies.csv
    boxoffice: https://raw.githubusercontent.com/freestackinitiative/teachingdb_data/main/data/core/boxoffice.csv
    employees: https://raw.githubusercontent.com/freestackinitiative/teachingdb_data/main/data/core/employees.csv
  
  ds_salaries:
    countries: https://raw.githubusercontent.com/freestackinitiative/teachingdb_data/main/data/ds_salaries/countries.csv
    ds_salaries: https://raw.githubusercontent.com/freestackinitiative/teachingdb_data/main/data/ds_salaries/ds_salaries.csv
    employment_types: https://raw.githubusercontent.com/freestackinitiative/teachingdb_data/main/data/ds_salaries/employment_types.csv
    experience_levels: https://raw.githubusercontent.com/freestackinitiative/teachingdb_data/main/data/ds_salaries/experience_levels.csv
    usd_exchange_rates: https://raw.githubusercontent.com/freestackinitiative/teachingdb_data/main/data/ds_salaries/usd_exchange_rates.csv